import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'core/formatting/unicode_formatter.dart';
import 'theme/app_theme.dart';

class ZaiblifyApp extends StatefulWidget {
  const ZaiblifyApp({super.key});
  @override State<ZaiblifyApp> createState() => _ZaiblifyAppState();
}
class _ZaiblifyAppState extends State<ZaiblifyApp> {
  ThemeMode _mode = ThemeMode.system;
  @override void initState() { super.initState(); _loadMode(); }
  Future<void> _loadMode() async { final p = await SharedPreferences.getInstance(); final v = p.getString('theme_mode'); if (mounted) setState(() => _mode = v == 'light' ? ThemeMode.light : v == 'dark' ? ThemeMode.dark : ThemeMode.system); }
  Future<void> setMode(ThemeMode mode) async { final p = await SharedPreferences.getInstance(); await p.setString('theme_mode', mode.name); if (mounted) setState(() => _mode = mode); }
  @override Widget build(BuildContext context) => MaterialApp(title: 'Zaiblify', debugShowCheckedModeBanner: false, theme: AppTheme.light, darkTheme: AppTheme.dark, themeMode: _mode, home: StartupGate(onThemeChanged: setMode));
}

class StartupGate extends StatefulWidget { final ValueChanged<ThemeMode> onThemeChanged; const StartupGate({super.key, required this.onThemeChanged}); @override State<StartupGate> createState() => _StartupGateState(); }
class _StartupGateState extends State<StartupGate> { bool ready = false, seen = false; @override void initState() { super.initState(); _prepare(); } Future<void> _prepare() async { await Future<void>.delayed(const Duration(milliseconds: 650)); final p = await SharedPreferences.getInstance(); if (mounted) setState(() { seen = p.getBool('seen_tour') ?? false; ready = true; }); } @override Widget build(BuildContext context) => !ready ? const SplashScreen() : seen ? ShellScreen(onThemeChanged: widget.onThemeChanged) : TourScreen(onFinished: () => setState(() => seen = true)); }

class Logo extends StatelessWidget { final double size; const Logo({super.key, this.size = 48}); @override Widget build(BuildContext context) => ClipRRect(borderRadius: BorderRadius.circular(size * .24), child: Image.asset('assets/branding/zaiblify_logo.png', width: size, height: size, fit: BoxFit.cover, errorBuilder: (_, __, ___) => Container(width: size, height: size, color: Theme.of(context).colorScheme.primary, child: Icon(Icons.auto_awesome_rounded, color: Theme.of(context).colorScheme.onPrimary, size: size * .5)))); }
class SplashScreen extends StatelessWidget { const SplashScreen({super.key}); @override Widget build(BuildContext context) => Scaffold(body: Center(child: Column(mainAxisSize: MainAxisSize.min, children: [const Logo(size: 92), const SizedBox(height: 22), Text('zaiblify', style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w900)), const SizedBox(height: 8), Text('by Zaib Labs', style: TextStyle(color: Theme.of(context).colorScheme.onSurfaceVariant))]))); }

class TourScreen extends StatefulWidget { final VoidCallback onFinished; const TourScreen({super.key, required this.onFinished}); @override State<TourScreen> createState() => _TourScreenState(); }
class _TourScreenState extends State<TourScreen> { final c = PageController(); int page = 0; final items = const [('Make words feel like you.', 'Turn ordinary text into expressive Unicode styles.', Icons.auto_awesome_rounded), ('Works where you write.', 'Use the editor now; Android text-selection integration comes next.', Icons.touch_app_rounded), ('Private by design.', 'Offline formatting, no account, and no AI required.', Icons.lock_outline_rounded)]; Future<void> finish() async { final p = await SharedPreferences.getInstance(); await p.setBool('seen_tour', true); widget.onFinished(); } @override Widget build(BuildContext context) { final item = items[page]; return Scaffold(body: SafeArea(child: Column(children: [Align(alignment: Alignment.centerRight, child: TextButton(onPressed: finish, child: const Text('Skip'))), Expanded(child: Padding(padding: const EdgeInsets.all(30), child: PageView.builder(controller: c, itemCount: items.length, onPageChanged: (v) => setState(() => page = v), itemBuilder: (_, i) { final x = items[i]; return Column(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 150, height: 150, decoration: BoxDecoration(shape: BoxShape.circle, color: Theme.of(context).colorScheme.primaryContainer), child: Icon(x.$3, size: 64, color: Theme.of(context).colorScheme.primary)), const SizedBox(height: 44), Text(x.$1, textAlign: TextAlign.center, style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900, letterSpacing: -1.5)), const SizedBox(height: 18), Text(x.$2, textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodyLarge?.copyWith(height: 1.5, color: Theme.of(context).colorScheme.onSurfaceVariant))]); } })), Row(mainAxisAlignment: MainAxisAlignment.center, children: List.generate(items.length, (i) => AnimatedContainer(duration: const Duration(milliseconds: 200), margin: const EdgeInsets.all(4), width: i == page ? 26 : 8, height: 8, decoration: BoxDecoration(color: i == page ? Theme.of(context).colorScheme.primary : Theme.of(context).colorScheme.outlineVariant, borderRadius: BorderRadius.circular(10))))), Padding(padding: const EdgeInsets.fromLTRB(24, 24, 24, 18), child: FilledButton(onPressed: () => page == items.length - 1 ? finish() : c.nextPage(duration: const Duration(milliseconds: 280), curve: Curves.easeOut), child: Text(page == items.length - 1 ? 'Get started' : 'Continue')))]))); }
}

class ShellScreen extends StatefulWidget { final ValueChanged<ThemeMode> onThemeChanged; const ShellScreen({super.key, required this.onThemeChanged}); @override State<ShellScreen> createState() => _ShellScreenState(); }
class _ShellScreenState extends State<ShellScreen> { int index = 0; @override Widget build(BuildContext context) { final pages = [const HomeScreen(), const EditorScreen(), const StylesScreen(), SettingsScreen(onThemeChanged: widget.onThemeChanged)]; return Scaffold(body: IndexedStack(index: index, children: pages), bottomNavigationBar: SafeArea(minimum: const EdgeInsets.fromLTRB(18, 0, 18, 14), child: Container(decoration: BoxDecoration(color: Theme.of(context).colorScheme.surface.withOpacity(.92), borderRadius: BorderRadius.circular(28), border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withOpacity(.5)), boxShadow: const [BoxShadow(blurRadius: 25, offset: Offset(0, 8))]), child: NavigationBar(selectedIndex: index, onDestinationSelected: (v) => setState(() => index = v), backgroundColor: Colors.transparent, elevation: 0, destinations: const [NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home_rounded), label: 'Home'), NavigationDestination(icon: Icon(Icons.edit_outlined), selectedIcon: Icon(Icons.edit_rounded), label: 'Editor'), NavigationDestination(icon: Icon(Icons.text_fields_rounded), label: 'Styles'), NavigationDestination(icon: Icon(Icons.tune_rounded), label: 'Settings')])))); } }

class HomeScreen extends StatelessWidget { const HomeScreen({super.key}); @override Widget build(BuildContext context) => SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(24, 28, 24, 130), children: [const Row(children: [Logo(size: 44), SizedBox(width: 12), Text('zaiblify', style: TextStyle(fontSize: 25, fontWeight: FontWeight.w900))]), const SizedBox(height: 42), Text('Make your words\nstand out.', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900, height: 1.05, letterSpacing: -1.8)), const SizedBox(height: 16), Text('A beautiful offline toolkit for expressive text.', style: Theme.of(context).textTheme.bodyLarge?.copyWith(color: Theme.of(context).colorScheme.onSurfaceVariant)), const SizedBox(height: 30), Card(child: Padding(padding: const EdgeInsets.all(22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Start styling', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 8), const Text('Write or paste text, choose a style, and copy the result.'), const SizedBox(height: 18), FilledButton.tonalIcon(onPressed: () {}, icon: const Icon(Icons.auto_awesome_rounded), label: const Text('Explore styles'))]))), const SizedBox(height: 30), Text('Popular styles', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 14), const Row(children: [Expanded(child: _Preview(label: 'Bold', text: '𝐇𝐞𝐥𝐥𝐨')), SizedBox(width: 12), Expanded(child: _Preview(label: 'Script', text: '𝓗𝓮𝓵𝓵𝓸'))]) ])); }
}
class _Preview extends StatelessWidget { final String label, text; const _Preview({required this.label, required this.text}); @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(text, style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 12), Text(label, style: TextStyle(color: Theme.of(context).colorScheme.primary, fontWeight: FontWeight.w700))]))); }

class EditorScreen extends StatefulWidget { const EditorScreen({super.key}); @override State<EditorScreen> createState() => _EditorScreenState(); }
class _EditorScreenState extends State<EditorScreen> { final input = TextEditingController(text: 'Hello Zaiblify'); ZaibStyle style = ZaibStyle.bold; @override Widget build(BuildContext context) { final output = UnicodeFormatter.apply(input.text, style); return SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(24, 28, 24, 130), children: [Text('Editor', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900, letterSpacing: -1.5)), const SizedBox(height: 10), Text('Transform text instantly, entirely offline.', style: TextStyle(color: Theme.of(context).colorScheme.onSurfaceVariant)), const SizedBox(height: 24), TextField(controller: input, maxLines: 5, onChanged: (_) => setState(() {}), decoration: const InputDecoration(labelText: 'Your text', hintText: 'Type or paste something…')), const SizedBox(height: 18), DropdownButtonFormField<ZaibStyle>(value: style, decoration: const InputDecoration(labelText: 'Style'), items: ZaibStyle.values.map((s) => DropdownMenuItem(value: s, child: Text(s.name))).toList(), onChanged: (v) => setState(() => style = v ?? style)), const SizedBox(height: 22), Card(child: Padding(padding: const EdgeInsets.all(20), child: SelectableText(output, style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w700))),), const SizedBox(height: 16), FilledButton.icon(onPressed: () => ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Copy action will be connected in the next integration phase.'))), icon: const Icon(Icons.copy_rounded), label: const Text('Copy result'))])); } }

class StylesScreen extends StatelessWidget { const StylesScreen({super.key}); @override Widget build(BuildContext context) => SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(24, 28, 24, 130), children: [Text('Styles', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900, letterSpacing: -1.5)), const SizedBox(height: 10), Text('Every style is generated offline.', style: TextStyle(color: Theme.of(context).colorScheme.onSurfaceVariant)), const SizedBox(height: 24), ...ZaibStyle.values.map((s) => Card(child: ListTile(title: Text(UnicodeFormatter.apply('Hello', s), style: Theme.of(context).textTheme.titleLarge), subtitle: Text(s.name), trailing: const Icon(Icons.chevron_right_rounded))))])); }

class SettingsScreen extends StatelessWidget { final ValueChanged<ThemeMode> onThemeChanged; const SettingsScreen({super.key, required this.onThemeChanged}); @override Widget build(BuildContext context) => SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(24, 28, 24, 130), children: [Text('Settings', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900, letterSpacing: -1.5)), const SizedBox(height: 24), Card(child: ListTile(leading: const Icon(Icons.brightness_6_rounded), title: const Text('Appearance'), subtitle: Text(Theme.of(context).brightness == Brightness.dark ? 'Dark theme active' : 'Light theme active'), onTap: () => showModalBottomSheet(context: context, builder: (_) => SafeArea(child: Column(mainAxisSize: MainAxisSize.min, children: [for (final x in [(ThemeMode.system, 'System default'), (ThemeMode.light, 'Light'), (ThemeMode.dark, 'Dark')]) ListTile(title: Text(x.$2), leading: Icon(x.$1 == ThemeMode.dark ? Icons.dark_mode : x.$1 == ThemeMode.light ? Icons.light_mode : Icons.settings_suggest), onTap: () { onThemeChanged(x.$1); Navigator.pop(context); })]))))), const Card(child: ListTile(leading: Icon(Icons.offline_bolt_rounded), title: Text('Formatting engine'), subtitle: Text('Unicode · Offline · No account')), const Card(child: ListTile(leading: Icon(Icons.business_rounded), title: Text('Zaib Labs'), subtitle: Text('Building simple, expressive tools'))])); }
